# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-ZH-ZhuYin
version:      0.02
version_from: lib/Lingua/ZH/ZhuYin.pm
installdirs:  site
requires:
    DBD::SQLite:                   0
    DBI:                           0
    Encode:                        0
    List::Util:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
